### ISSUE TITLE
rule and route deletion does not work

### ISSUE THREAD

**Issue by teedu** [liske/ifstate#12]
I'm experiencing a strange behavior. Adding rules and routes work fine, but deleting them is not working (ifstate just ignores them).
Relevant config below:

``` 
cat /etc/ifstate/config.yml
routing:
  routes:
  - to: 0.0.0.0/0
    dev: ipsec1
    proto: boot
    table: client
  rules:
  - table: client
    priority: 100
    from: 172.16.4.0/23
```
```
ifstatecli show
rrouting:
  routes:
  - to: 0.0.0.0/0
    table: !!python/tuple
    - client
    dev: ipsec1
  rules:
  - table: 100
    priority: 100
    family: 2
    from: 172.16.4.0/23
``` 
```
ifstatecli check
configuring routing table main...

configuring routing table client...
 0.0.0.0/0       ok

configuring routing rules...
 #100            ok
``` 

If I want to remove either rule or route, ifstatecli simply ignores them:
``` 
cat /etc/ifstate/config.yml
#routing:
#  routes:
#  - to: 0.0.0.0/0
#    dev: ipsec1
#    proto: boot
#    table: client
#  rules:
#  - table: client
#    priority: 100
#    from: 172.16.4.0/23
``` 
``` 
ifstatecli check
returns nothing about rules or routes
``` 
```
ifstatecli show
routing:
  routes:
  - to: 0.0.0.0/0
    table: !!python/tuple
    - client
    dev: ipsec1
  rules:
  - table: 100
    priority: 100
    family: 2
    from: 172.16.4.0/23
``` 
Am I doing something completely wrong? Or is it expected behavior?
