### ISSUE TITLE
Unexpected Router Impact and Interface Unconfiguration When Creating Geneve Tunnel with Ifstatecli

### ISSUE THREAD

**Issue by maxadamo** [liske/ifstate#25]
I used your provided example to create a Geneve tunnel, and then I made a modification by adding a second Tunnel (gen1). Below is the YAML configuration I used: 

```yaml
interfaces:
- name: br0
  link:
    kind: bridge
    br_stp_state: 0
    state: up
- name: eth1
  link:
    kind: physical
    master: br0
    state: up
- name: gen0
  link:
    kind: geneve
    geneve_id: 42
    geneve_remote: 192.168.100.2
    master: br0
    state: up
- name: gen1
  link:
    kind: geneve
    geneve_id: 42
    geneve_remote: 192.168.100.3
    master: br0
    state: up
```

After running the following command to apply the configuration:
 
```
ifstatecli -c /etc/ifstate/cni.yaml apply
```

the tool brought down all other interfaces, resulting in my VM becoming unreachable. I looked for a way to add the other interfaces to an ignore list but couldn't find any. I'm puzzled as to why the tool wants to unconfigure the other interfaces, and this behavior seems undesirable. Normally, when using tools like Netplan or Systemd, they only attempt to configure the interfaces explicitly mentioned in the configuration file, leaving other interfaces unaffected.

To resolve the issue, I accessed the console and ran `netplan apply`. After doing so, the VM became reachable again, but it stopped replying to ping requests. 
_Another user suggested that my VM was replying ICMP request on behalf of the router._ **If the assertion of my colleagues is true, would you be able to understand what might have happened?** 

**Expected Outcome:**

As a matter of principle, the `ifstatecli` should not make changes to interfaces that are not explicitly mentioned in the provided configuration file. The tool should only configure the interfaces specified in the YAML, similar to the behavior of Netplan or Systemd.

**Comment by maxadamo** [comment]
please note, if I apply your configuration using the command line (using your example) nothing happens. It was the combination of `istatecli apply` + `netplan apply`

**Comment by maxadamo** [comment]
impact on router was caused by STP disabled, which caused a loop:
```yaml
br_stp_state: 0
```

**Comment by liske** [comment]
> **Expected Outcome:**
> 
> As a matter of principle, the `ifstatecli` should not make changes to interfaces that are not explicitly mentioned in the provided configuration file. The tool should only configure the interfaces specified in the YAML, similar to the behavior of Netplan or Systemd.

Sorry to hear that you broke your setup. But this behavior **is** intentional! Ifstate uses a declarative approach and it is essential to remove (or disable physical links) any interfaces which has no explicit state defined. 

![image](https://github.com/liske/ifstate/assets/372458/fa4f5bf5-399a-4a56-a101-c594a1aac374)

To extend the list of ignored interfaces take a look at the schema: https://ifstate.net/schema/#ignore

```yaml

ignore:
  ifname:
    - ^eth42$
```
